# Generated by Django 2.2.7 on 2019-11-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fortest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testlogin', models.CharField(max_length=10)),
                ('testpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
